// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package flymqv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FlyMQServiceClient is the client API for FlyMQService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlyMQServiceClient interface {
	// Produce sends a message or a batch of messages to a topic.
	Produce(ctx context.Context, in *ProduceRequest, opts ...grpc.CallOption) (*ProduceResponse, error)
	// Consume opens a stream to receive messages from a topic.
	Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (FlyMQService_ConsumeClient, error)
	// GetMetadata retrieves information about topics and the cluster.
	GetMetadata(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error)
}

type flyMQServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlyMQServiceClient(cc grpc.ClientConnInterface) FlyMQServiceClient {
	return &flyMQServiceClient{cc}
}

func (c *flyMQServiceClient) Produce(ctx context.Context, in *ProduceRequest, opts ...grpc.CallOption) (*ProduceResponse, error) {
	out := new(ProduceResponse)
	err := c.cc.Invoke(ctx, "/flymq.v1.FlyMQService/Produce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flyMQServiceClient) Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (FlyMQService_ConsumeClient, error) {
	stream, err := c.cc.NewStream(ctx, &FlyMQService_ServiceDesc.Streams[0], "/flymq.v1.FlyMQService/Consume", opts...)
	if err != nil {
		return nil, err
	}
	x := &flyMQServiceConsumeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FlyMQService_ConsumeClient interface {
	Recv() (*ConsumeResponse, error)
	grpc.ClientStream
}

type flyMQServiceConsumeClient struct {
	grpc.ClientStream
}

func (x *flyMQServiceConsumeClient) Recv() (*ConsumeResponse, error) {
	m := new(ConsumeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *flyMQServiceClient) GetMetadata(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error) {
	out := new(MetadataResponse)
	err := c.cc.Invoke(ctx, "/flymq.v1.FlyMQService/GetMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlyMQServiceServer is the server API for FlyMQService service.
// All implementations must embed UnimplementedFlyMQServiceServer
// for forward compatibility
type FlyMQServiceServer interface {
	// Produce sends a message or a batch of messages to a topic.
	Produce(context.Context, *ProduceRequest) (*ProduceResponse, error)
	// Consume opens a stream to receive messages from a topic.
	Consume(*ConsumeRequest, FlyMQService_ConsumeServer) error
	// GetMetadata retrieves information about topics and the cluster.
	GetMetadata(context.Context, *MetadataRequest) (*MetadataResponse, error)
	mustEmbedUnimplementedFlyMQServiceServer()
}

// UnimplementedFlyMQServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFlyMQServiceServer struct {
}

func (UnimplementedFlyMQServiceServer) Produce(context.Context, *ProduceRequest) (*ProduceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Produce not implemented")
}
func (UnimplementedFlyMQServiceServer) Consume(*ConsumeRequest, FlyMQService_ConsumeServer) error {
	return status.Errorf(codes.Unimplemented, "method Consume not implemented")
}
func (UnimplementedFlyMQServiceServer) GetMetadata(context.Context, *MetadataRequest) (*MetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedFlyMQServiceServer) mustEmbedUnimplementedFlyMQServiceServer() {}

// UnsafeFlyMQServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlyMQServiceServer will
// result in compilation errors.
type UnsafeFlyMQServiceServer interface {
	mustEmbedUnimplementedFlyMQServiceServer()
}

func RegisterFlyMQServiceServer(s grpc.ServiceRegistrar, srv FlyMQServiceServer) {
	s.RegisterService(&FlyMQService_ServiceDesc, srv)
}

func _FlyMQService_Produce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProduceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlyMQServiceServer).Produce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flymq.v1.FlyMQService/Produce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlyMQServiceServer).Produce(ctx, req.(*ProduceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlyMQService_Consume_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConsumeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FlyMQServiceServer).Consume(m, &flyMQServiceConsumeServer{stream})
}

type FlyMQService_ConsumeServer interface {
	Send(*ConsumeResponse) error
	grpc.ServerStream
}

type flyMQServiceConsumeServer struct {
	grpc.ServerStream
}

func (x *flyMQServiceConsumeServer) Send(m *ConsumeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _FlyMQService_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlyMQServiceServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flymq.v1.FlyMQService/GetMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlyMQServiceServer).GetMetadata(ctx, req.(*MetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlyMQService_ServiceDesc is the grpc.ServiceDesc for FlyMQService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlyMQService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flymq.v1.FlyMQService",
	HandlerType: (*FlyMQServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Produce",
			Handler:    _FlyMQService_Produce_Handler,
		},
		{
			MethodName: "GetMetadata",
			Handler:    _FlyMQService_GetMetadata_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Consume",
			Handler:       _FlyMQService_Consume_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "flymq.proto",
}
