// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flymq.proto

package flymqv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProduceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic     string            `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition int32             `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Key       []byte            `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value     []byte            `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Headers   map[string]string `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Messages  []*Message        `protobuf:"bytes,6,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *ProduceRequest) Reset() {
	*x = ProduceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flymq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceRequest) ProtoMessage() {}

func (x *ProduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flymq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProduceRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ProduceRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ProduceRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ProduceRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ProduceRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ProduceRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     []byte            `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value   []byte            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Headers map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flymq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_flymq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Message) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Message) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Message) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type ProduceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset    uint64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Partition int32  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Error     string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ProduceResponse) Reset() {
	*x = ProduceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flymq_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceResponse) ProtoMessage() {}

func (x *ProduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flymq_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProduceResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ProduceResponse) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ProduceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConsumeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic       string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition   int32  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset      uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	GroupId     string `protobuf:"bytes,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MaxMessages int32  `protobuf:"varint,5,opt,name=max_messages,json=maxMessages,proto3" json:"max_messages,omitempty"`
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flymq_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flymq_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConsumeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ConsumeRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ConsumeRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ConsumeRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ConsumeRequest) GetMaxMessages() int32 {
	if x != nil {
		return x.MaxMessages
	}
	return 0
}

type ConsumeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset    uint64            `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Key       []byte            `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value     []byte            `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Headers   map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Timestamp int64             `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flymq_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flymq_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConsumeResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ConsumeResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ConsumeResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ConsumeResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ConsumeResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type MetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topics []string `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flymq_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flymq_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MetadataRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type MetadataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topics   []*TopicMetadata `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	Brokers  []*BrokerNode    `protobuf:"bytes,2,rep,name=brokers,proto3" json:"brokers,omitempty"`
	LeaderId string           `protobuf:"bytes,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flymq_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flymq_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MetadataResponse) GetTopics() []*TopicMetadata {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *MetadataResponse) GetBrokers() []*BrokerNode {
	if x != nil {
		return x.Brokers
	}
	return nil
}

func (x *MetadataResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

type TopicMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Partitions []*PartitionMetadata `protobuf:"bytes,2,rep,name=partitions,proto3" json:"partitions,omitempty"`
}

func (x *TopicMetadata) Reset() {
	*x = TopicMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flymq_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopicMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicMetadata) ProtoMessage() {}

func (x *TopicMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_flymq_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TopicMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopicMetadata) GetPartitions() []*PartitionMetadata {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type PartitionMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Leader   string   `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	Replicas []string `protobuf:"bytes,3,rep,name=replicas,proto3" json:"replicas,omitempty"`
	Isr      []string `protobuf:"bytes,4,rep,name=isr,proto3" json:"isr,omitempty"`
}

func (x *PartitionMetadata) Reset() {
	*x = PartitionMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flymq_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartitionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionMetadata) ProtoMessage() {}

func (x *PartitionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_flymq_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PartitionMetadata) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PartitionMetadata) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

func (x *PartitionMetadata) GetReplicas() []string {
	if x != nil {
		return x.Replicas
	}
	return nil
}

func (x *PartitionMetadata) GetIsr() []string {
	if x != nil {
		return x.Isr
	}
	return nil
}

type BrokerNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *BrokerNode) Reset() {
	*x = BrokerNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flymq_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrokerNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerNode) ProtoMessage() {}

func (x *BrokerNode) ProtoReflect() protoreflect.Message {
	mi := &file_flymq_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BrokerNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BrokerNode) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_flymq_proto protoreflect.FileDescriptor

var file_flymq_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x66, 0x6c, 0x79, 0x6d, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x66,
	0x6c, 0x79, 0x6d, 0x71, 0x2e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_flymq_proto_rawDescOnce sync.Once
	file_flymq_proto_rawDescData = file_flymq_proto_rawDesc
)

func file_flymq_proto_rawDescGZIP() []byte {
	file_flymq_proto_rawDescOnce.Do(func() {
		file_flymq_proto_rawDescData = protoimpl.X.CompressGZIP(file_flymq_proto_rawDescData)
	})
	return file_flymq_proto_rawDescData
}

var file_flymq_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_flymq_proto_goTypes = []interface{}{
	(*ProduceRequest)(nil),    // 0: flymq.v1.ProduceRequest
	(*Message)(nil),           // 1: flymq.v1.Message
	(*ProduceResponse)(nil),   // 2: flymq.v1.ProduceResponse
	(*ConsumeRequest)(nil),    // 3: flymq.v1.ConsumeRequest
	(*ConsumeResponse)(nil),   // 4: flymq.v1.ConsumeResponse
	(*MetadataRequest)(nil),    // 5: flymq.v1.MetadataRequest
	(*MetadataResponse)(nil),   // 6: flymq.v1.MetadataResponse
	(*TopicMetadata)(nil),     // 7: flymq.v1.TopicMetadata
	(*PartitionMetadata)(nil), // 8: flymq.v1.PartitionMetadata
	(*BrokerNode)(nil),        // 9: flymq.v1.BrokerNode
	nil,                       // 10: flymq.v1.ProduceRequest.HeadersEntry
	nil,                       // 11: flymq.v1.ConsumeResponse.HeadersEntry
}
var file_flymq_proto_depIdxs = []int32{
	10, // 0: flymq.v1.ProduceRequest.headers:type_name -> flymq.v1.ProduceRequest.HeadersEntry
	1,  // 1: flymq.v1.ProduceRequest.messages:type_name -> flymq.v1.Message
	11, // 2: flymq.v1.ConsumeResponse.headers:type_name -> flymq.v1.ConsumeResponse.HeadersEntry
	7,  // 3: flymq.v1.MetadataResponse.topics:type_name -> flymq.v1.TopicMetadata
	9,  // 4: flymq.v1.MetadataResponse.brokers:type_name -> flymq.v1.BrokerNode
	8,  // 5: flymq.v1.TopicMetadata.partitions:type_name -> flymq.v1.PartitionMetadata
	0,  // 6: flymq.v1.FlyMQService.Produce:input_type -> flymq.v1.ProduceRequest
	3,  // 7: flymq.v1.FlyMQService.Consume:input_type -> flymq.v1.ConsumeRequest
	5,  // 8: flymq.v1.FlyMQService.GetMetadata:input_type -> flymq.v1.MetadataRequest
	2,  // 9: flymq.v1.FlyMQService.Produce:output_type -> flymq.v1.ProduceResponse
	4,  // 10: flymq.v1.FlyMQService.Consume:output_type -> flymq.v1.ConsumeResponse
	6,  // 11: flymq.v1.FlyMQService.GetMetadata:output_type -> flymq.v1.MetadataResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_flymq_proto_init() }
func file_flymq_proto_init() {
	return
}
